### PR TITLE
getPullRequests method

### PR DESCRIPTION
**Pull request by vectart**

### CODE REVIEW

**Comment by ingshtrom** [comment]
I haven't looked at this project in a while, but I'll take anything :P

**Comment by vectart** [comment]
@ingshtrom It works, thank you!

**Comment by ingshtrom** [comment]
@vectart I'm curious what sort of project you are working on that is consuming this?

**Comment by vectart** [comment]
@ingshtrom It's used as part of internal [Klarna Checkout](https://klarna.com/) development tool.

**Pull request merged**
